[versions]
agp = "8.7.0"
kotlin = "2.0.21"
xposed = "82"
ezXHelper = "2.2.0"

[libraries]
xposed = { module = "de.robv.android.xposed:api", version.ref = "xposed" }
ezXHelper = {module = "com.github.kyuubiran:EzXHelper", version.ref = "ezXHelper"}

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

